### ISSUE TITLE
uni-app支持

### ISSUE THREAD

**Issue by tpxiang** [weimob-tech/WeConsole#2]
请问支持uni-app微信小程序吗

**Comment by imingyu** [comment]
uniapp 是可以运行的，只有把weconsole/dist/full目录复制到已经编译好的uniapp目录中，然后在app.js中引入full/init.js是可以用的。

![image](https://github.com/weimob-tech/WeConsole/assets/7113267/d8fe93bd-0f80-49ea-b539-f39e5c7925a4)
